version: '3.2'

services:
   db:
      image: mysql:8.0
      container_name: mysql
      restart: always
      ports:
       - '3306:3306'
      environment:
        MYSQL_ROOT_PASSWORD: bds29

   phpmyadmin:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '8899:80'
      environment:
        PMA_HOST: db
