version: '3.2'
services:
   redis:
      # https://citizix.com/how-to-run-redis-6-with-docker-and-docker-compose/
      image: redis:6.2-alpine
      container_name: redis
      restart: always
      ports:
        - '6379:6379'
      command: redis-server --save 60 1 --requirepass MDNcVb924a --loglevel warning
   mysql:
      image: mysql:8.0
      container_name: mysql
      restart: always
      ports:
         - '3306:3306'
      environment:
         MYSQL_ROOT_PASSWORD: bds29
   phpmyadmin:
      depends_on:
         - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
         - '8899:80'
      environment:
         PMA_HOST: db