version: '3.2'
services:
   redis:
      # https://citizix.com/how-to-run-redis-6-with-docker-and-docker-compose/
      image: redis:6.2-alpine
      container_name: redis
      restart: on-failure
      ports:
        - '6379:6379'
      command: redis-server --save 60 1 --requirepass xxxxxxxx --loglevel warning
   mariadb:
      image: mariadb:10.2
      container_name: mariadb
      restart: on-failure
      ports:
         - '3306:3306'
      environment:
         MYSQL_ROOT_PASSWORD: bds29
   phpmyadmin:
      depends_on:
         - mariadb
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: on-failure
      ports:
         - '8899:80'
      environment:
         PMA_HOST: mariadb